telegram_bot_token: ENC[AES256_GCM,data:025ynbTMt90243v0Dz7b5v5xb5kdlRJpv2aAPWYP+OBkw66d1B18DDByGbYpBw==,iv:OLhyAOhlpZbEFFxctWRibYRCcfYFFQwV/kfdN/bF6EA=,tag:Szho9VIGt/zw7qHaFuEPBg==,type:str]
openrouter_api_key: ENC[AES256_GCM,data:Cf3VZENP0HKxtGByOk7cpEdqVQO0oZhpKVn2TSaLrHYnWTVm7XuLlxNvsr9j7Mbp/8gULaOE/vmutdOKqKZzArF835MkBLXVow==,iv:AIqU62ygdIiJS1RuM/1IG7JUdF5Bn7to4z7O78tYU1w=,tag:bUfm36CueTx39oD5cElN9g==,type:str]
data_dir: ENC[AES256_GCM,data:Rji6rFge,iv:IDWSAyDq9NUYA3T1BJB/2k7ADYuGS4EJnZQJ3nC0gNY=,tag:E1AcYq1DQGbQWpAiWSH8AQ==,type:str]
http_port: ENC[AES256_GCM,data:uN2lYQ==,iv:4EjoC3T9htPARSGRXVYbWu9pMj6sK3456SOBCsaUdK8=,tag:Vn8SejeNsHj728W2GiM2YA==,type:str]
log_level: ENC[AES256_GCM,data:zG0TYpI=,iv:pObJcC2GraUgX7jg0X5D8A2GgBofa+hEAbrIk8PEYhQ=,tag:TRJEiJLcLdUiw6n/Jf/JHw==,type:str]
openrouter_model: ENC[AES256_GCM,data:ze9kRMaPIQXj5I510cnD1VnOCZLAwWEdRZgDiSE=,iv:62IQPvH+eWpD9BMFcb5K0nMM2v0NfBAKB8xTo/0CRvc=,tag:IPFJ8oP9BrhEK/VBKWe5/A==,type:str]
webapp_url: ""
sops:
    age:
        - recipient: age1n4r6cd5y9ay0dff9592yspp6u5vhlc6ymecx529dgyfd62sw0crqujv00x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNVl0Q1p3SVR0ZnZZaWdR
            dkY1ekljcmNLSFRBa3Bhb0RTUFl0SzQ1eVRNCnNMUEF6Z2F3ZXY4L21PMzVKdWpS
            VEtnK08rMGlZeXUxTHdRbHRwMnV2YUUKLS0tIE5JTm1McVJyTXBpOGlYSjhSVjRM
            MTUwaE1UMERvNGpJazVlM1B4VG9HWjAKKtg0mC0BVZPAR3Bg3MJK3OM8Dfanq3NI
            zd/xQ5t4TBy7h6Zd2tIRSoDXFT3XsYG544DiWfCr2TTV/lDAK9jWeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c6628acj4gredlt2m99p43lc49ajzgsuurtyfrcmjrqh8zdr2q0q6wztnx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM3JpOWFaZUZrTUFPbkNn
            clUyRjgxRmtYR2F3T2JOTUU4RUNaUDFoaEZjCjBLUTJLNC9SODFoRUxEYnBEejdp
            TEUrMFZxLzlFYWgrNDZTMng4ZjhvT1EKLS0tIHp4M3g1cHpoUEdFTU13cnJEdGRH
            RWFqQUFTNHFuVnJTYmhoeis5cG5rbGcKp9C9OZn1xdacuFRTo24hxc4M8NOYd+pi
            oRAmEC0+wxLrEOxSx+yy5ZlKbiH8w+zgxRK8Kf+aowPQUDWi66pT3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T13:20:31Z"
    mac: ENC[AES256_GCM,data:pQmgqSt88HcO7nPPkFL30lHnmz55jGB8g2kqr91BMSrtK90le8diTTyI9xnna353/HqrfJGI72f2wMA1vMS5nit1y89I7xhW99iY5CMVuH8YjMl0ShOvruA9gC9yLBfGmOOh+t4NIaLKF13YXMLvqBjCBp+Zk6tMqx3nmfxQEzg=,iv:c8Y/WolrbCYpq6TQKpfD+OaI9PeZrLxDYIMwySeKe+0=,tag:wHEC1RThuGotxOPqN3TjDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
